### PR TITLE
Apply accessiblity focus fixes to identity ui controls too

### PR DESCRIPTION
**Pull request by HaoK**
Similar to https://github.com/dotnet/spa-templates/commit/bbd5404010791a6c0f364cd2b7ed1cd4b2846864

### CODE REVIEW

**Review by sebastienros — APPROVED** [review]

**Comment by sebastienros** [comment]
We don't generate any minified/bundled versions of these scripts?

**Comment by HaoK** [comment]
Not sure, but the previous update to these files didn't change anything else 🤷‍♂️

**Comment by HaoK** [comment]
@dougbu we don't have to manually update the submodule in aspnetcore to pickup these changes anymore right? I'm asking because I don't see these spa changes in a new app I just created from dotnet/installer.  But it looks like the submodules already have this from: 

https://github.com/dotnet/aspnetcore/pull/43289

**Comment by dougbu** [comment]
> @dougbu we don't have to manually update the submodule in aspnetcore to pickup these changes anymore right?

Depends entirely on urgency. Dependabot will update all submodules (if there's anything new) every Monday morning. But if you need something sooner, manual updates are the way to go.

Dependabot isn't like `darc` in that I don't see a way to trigger something like a submodule check off-schedule.

**Pull request merged**
