### PR TITLE
Proposed PR for https://github.com/dotnet/aspnetcore/issues/46134

### PR DESCRIPTION
**Pull request by shiladitya-mukerji-22**
**Description:**

This issue is registered at https://github.com/dotnet/aspnetcore/issues/46134. 

Added --check and --trust options to dotnet dev-cert https command.

Issue #46134

### CODE REVIEW

**Comment by shiladitya-mukerji-22** [comment]
@javiercn Can you please review my code.

**Comment by javiercn** [comment]
This won't do what you expect.

`check` specifically avoids doing any change to the system.

`trust` will trigger a prompt, which is not something we want to do from the CLI

**Comment by shiladitya-mukerji-22** [comment]
> @shiladitya-mukerji-22 `--check` does not validate files on disk, it validates the current installed cert.
> 
> The tool does not know anything about files on disk.

Hi @javiercn. I have made a few changes. Can you please review my code.

**Comment by mkArtakMSFT** [comment]
Thank you for your effort.
As you may have seen already, we have decided to remove the SPA project templates from the .NET 8 SDK. As a result, this repo will now be used only for servicing, and we will not be taking any new changes here for non-servicing related needs.

**Pull request closed without merging**
