### PR TITLE
[SPA] Update SPA templates NPM dependencies

### PR DESCRIPTION
**Pull request by javiercn**
## Description

Updates our SPA template dependencies as part of our regular update schedule on patch releases. This update contains an update from Angular 12 to Angular 13.

The update to the angular version has been performed by automation with `ng update`.

## Customer Impact

Templates contain a set of fixed package versions that get regularly out of date and start producing security warnings. As part of our regular patch process we update these dependencies to keep our customers protected and make sure they don't have a bad experience due to security warnings appearing after project creation

## Regression?

- [ ] Yes
- [X] No

## Risk

- [ ] High
- [ ] Medium
- [X] Low

We do this process regularly. 

## Verification

- [X] Manual (required)
- [ ] Automated

Validated:
* run Angular Individual auth on windows
* run Angular no auth Individual auth on windows
* run React Individual auth on windows
* run React no auth on windows
* Publish angular individual auth on Windows.
* Publish react individual auth on Windows.

Updating package dependencies is not sensitive to OS issues.

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [X] N/A

### CODE REVIEW

**Review by pranavkm — APPROVED** [review]

**Comment by wtgodbe** [comment]
Can you port this to main also?

**Comment by javiercn** [comment]
@wtgodbe will do. Wanted to make sure to get it in 6.0 first

**Comment by mkArtakMSFT** [comment]
@wtgodbe  I'm merging this now. Can you please make sure that we get this update through submodule update in aspnetcore ?

**Comment by wtgodbe** [comment]
Will do

**Pull request merged**
