### PR TITLE
Update React and Angular project template dependencies

### PR DESCRIPTION
**Pull request by MackinnonBuck**
### Summary

The Angular template's dependencies were straightforward to update.

The React template's updated dependencies had a lot of breaking changes, so a fair amount of JavaScript had to be updated/rewritten. The primary refactoring involved routing and authentication. I also fixed formatting issues here and there (e.g., changed files that were using 4-space indentation to instead use 2-space indentation).

### Validation
Manually tested both templates with and without individual authentication.

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by MackinnonBuck** [comment]
Also validated published builds on Windows and macOS.

**Review by javiercn — APPROVED** [review]
Great job!

Looks great!

**Comment by mkArtakMSFT** [comment]
@MackinnonBuck are you also taking care of updating the submodule in dotnet/aspnetcore repo to pull this change in for 6.0?

**Comment by MackinnonBuck** [comment]
@mkArtakMSFT sure, I'll handle that as well

**Comment by wtgodbe** [comment]
> @MackinnonBuck are you also taking care of updating the submodule in dotnet/aspnetcore repo to pull this change in for 6.0?

This is the `main` branch, we'd need to backport this to https://github.com/dotnet/spa-templates/tree/release/6.0 to get it in to aspnetcore's release/6.0 branch

**Comment by wtgodbe** [comment]
For `main`, I'm going to get this in to https://github.com/dotnet/aspnetcore/pull/41485

**Pull request merged**
