### PR TITLE
Update to net7

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
WFM

**Comment by wtgodbe** [comment]
@dougbu rc2 isn't quite dead yet, could you merge this next week when it is? release/6.0 in aspnetcore is already updated to use the release/6.0 branch, but release/6.0-rc2 isn't

**Comment by dougbu** [comment]
> could you merge this next week when it is?

certainly

**Comment by dougbu** [comment]
side note: no submodule would be auto-updated in our RC2 branch; Dependabot is configured to ignore every branch other than 'release/2.1', 'release/3.1', 'release/5.0', 'release/6.0' and 'main'. Further, the .github/dependabot.yml file in other branches (if any) is ignored.

**Pull request merged**
