### PR TITLE
Update name of TemplateEngine package

### PR DESCRIPTION
**Pull request by wtgodbe**
https://github.com/dotnet/arcade/pull/11866 for context. Part of unblocking https://github.com/dotnet/aspnetcore/pull/45553

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Comment by dougbu** [comment]
@wtgodbe @vlada-shubina @riarenas have we discussed how we're going to keep this package version up to date❔ I'm guessing we could either make the chosen version available from the Arcade SDK or add our own subscription here. Either works for me but I'm off for the rest of the year (after today) and don't want to vote.

**Comment by wtgodbe** [comment]
There's a subscription into Arcade now, so we could choose to delete our property and just use theirs

**Comment by dougbu** [comment]
> There's a subscription into Arcade now, so we could choose to delete our property and just use theirs

I think that requires a change somewhere in the Arcade SDK to carry the `$(MicrosoftTemplateEngineAuthoringTasksVersion)` along. Is that correct @riarenas❔

**Comment by dougbu** [comment]
This is exactly what I meant w/ my first option.

**Comment by riarenas** [comment]
@vlada-shubina is working on getting this working. The subscription was set up but the initial rename missed a property and was fixed in https://github.com/dotnet/arcade/pull/11921

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade/pull/11921 will need to flow first, but yeah, afterwards it should be possible to remove the property.

**Pull request merged**
