### PR TITLE
Fix Component Governance alerts

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Review by HaoK — APPROVED** [review]

**Comment by mkArtakMSFT** [comment]
Thanks @wtgodbe.
@MackinnonBuck can you please see whether this is something to go well with your changes or should these be merged together? Thanks!

**Comment by MackinnonBuck** [comment]
It might be the case that these steps should be repeated on #47. I'm not sure if these two PRs are compatible.

**Comment by mkArtakMSFT** [comment]
@MackinnonBuck, @wtgodbe we need Mackinnon's changes. But we also need to make sure we address CG alerts. So please work together to unify the changes into a single PR.

**Comment by wtgodbe** [comment]
Closing in favor of https://github.com/dotnet/spa-templates/pull/47

**Pull request closed without merging**
