### PR TITLE
Extend SkipSpaBuild condition to require node_modules.

### PR DESCRIPTION
**Pull request by tmds**
@javiercn ptal.

This extends the SkipSpaBuild condition so it requires some SPA artifacts be present.

### CODE REVIEW

**Comment by tmds** [comment]
@javiercn we need this (or something else) to avoid `dotnet publish -c Release` being successful without there being a front-end.

**Comment by javiercn** [comment]
@tmds I am not sure I understand what is failing here.

**Comment by javiercn** [comment]
We should just put the condition on the targets `https://github.com/dotnet/spa-templates/pull/62/files#diff-fcd8e31c03a88a07e2a5342f977ea17e0c5120f39849d54fa335e29446e21d42R58

**Comment by tmds** [comment]
> @tmds I am not sure I understand what is failing here.

With the current changes, if you publish the app in a .NET container, the operation succeeds, but no front-end is built.
If the front-end is missing, the build must fail.

**Comment by javiercn** [comment]
> With the current changes, if you publish the app in a .NET container, the operation succeeds, but no front-end is included.
> If the front-end is missing, the build must fail.

I am started to be confused about how all this is supposed to work, and I think we might have rushed with the other PR.

I would like us to step back and see exactly what the docker file looks like and what the csproj looks like, as well as the commands to run in the issue before we keep making changes.

**Comment by tmds** [comment]
The Dockerfile looks like the one in https://github.com/dotnet/aspnetcore/issues/41275.

From the first stage (nodejs) to the second stage (.NET) we copy over the `SpaRoot`.

> We should just put the condition on the targets `https://github.com/dotnet/spa-templates/pull/62/files#diff-fcd8e31c03a88a07e2a5342f977ea17e0c5120f39849d54fa335e29446e21d42R58

We can't put the condition here. This is responsible for copying over from the `SpaRoot` to the proper output location.

> I would like us to step back and see exactly what the docker file

The way the changes are implemented now has one issue.

If you publish this template in a .NET container build, you get:

```
/tmp/angular$ dotnet publish -c Release
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  angular -> /tmp/angular/bin/Release/net6.0/angular.dll
  angular -> /tmp/angular/bin/Release/net6.0/publish/
```

That is: the publish is successful.

It should fail because the front-end is missing.

**Comment by javiercn** [comment]
@tmds I think I understand now where the disconnect is.

I expect the docker file to be something like this:
```diff
#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["AngularWithDocker/AngularWithDocker.csproj", "AngularWithDocker/"]
RUN dotnet restore "AngularWithDocker/AngularWithDocker.csproj"
COPY . .
WORKDIR "/src/AngularWithDocker"
RUN dotnet build "AngularWithDocker.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AngularWithDocker.csproj" -c Release -o /app/publish

+FROM node:lts-alpine as node-build
+# Copy the contents of ClientApp to src
+# WORKDIR src
+RUN npm install
+RUN npm run build -- --prod

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
+COPY --from=node-build /src/Dist ./wwwroot
ENTRYPOINT ["dotnet", "AngularWithDocker.dll"]
```

**Comment by tmds** [comment]
I think we should avoid:
- `dotnet publish -c Release` succeeds when there is no front-end
- Duplicating logic from the csproj target to the Dockerfile

**Comment by javiercn** [comment]
> I think it's preferable to keep using the csproj target for copying from the SpaRoot. The target is already different between angular and react, a user can customize it further.
> 
> If we don't use the target, these differences spill into the Dockerfile.

I think that's fine, you are already doing the build for the node dependencies in the docker file, I rather do the copying there too rather than doing half the work on the dockerfile and half the work in the csproj. It creates a coupling that is not obvious to the consumer.

**Comment by javiercn** [comment]
@tmds I think that in the case of docker, we should make sure that no node/js related targets get to run ever, and that building and putting the assets in the final location happens independently of .NET. 

Otherwise, I would just prefer for the docker file to install the node dependencies and for the build to proceed as normal, in which case we wouldn't need any of this.

**Comment by tmds** [comment]
We want the app that gets built by the Dockerfile to behave the same as the app the user builds from the csproj file.

I see no benefits in duplicating the logic from the csproj target to the Dockerfile.

It introduces the risk they do something different.
And, it makes the Dockerfile more complex.

**Comment by javiercn** [comment]
@tmds I played with this a bit and I think we are going in the wrong direcion here.

It is simpler to add the snippet below to the template than deal with this approach.
```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-with-spa
RUN bash -E $(curl -fsSL https://deb.nodesource.com/setup_18.x | bash - ); apt install -y nodejs

From build-with-spa as build
...
```

**Comment by javiercn** [comment]
@richlander would it be possible for us to have a docker image with node installed that people could use? This is a common scenario for web applications and it would be best handled by our official images rather than asking users to do things.

**Comment by javiercn** [comment]
@tmds I don't think we need to cover every possible docker build scenario and I believe that these changes add a lot of complexity that the majority of our users don't need.

For users doing this, there is a simple solution like the one described above which will work for the vast majority of them.

For those that want something more advanced and based on the complexity surfaced here, I rather us cover this in docs than in the templates themselves. 

I am ok with having a flag to NO-OP all JS behavior from the project file so that it doesn't get in the way and handling the SPA bits externally in the Dockerfile. 

I am not ok with us creating coupling between the project file and the docker file where the dockerfile is responsible for the build and the project file is responsible for the copying and you need to carefully orchestrate those two things. 

It makes it hard for users to know what is going on, it makes it fragile for us to make changes without accidentally breaking the scenario (as any change to the csproj file needs to be potentially in sync with the dockerfile) and it adds complexity to the templates that the majority of our users don't have to deal with.

I rather us focus on making it work as it does today without containers, which is simpler and if we choose to do so, document this approach. I, however, don't think this is the right starting point for our users for the reasons described above.

I apologize for the back and forth here, I originally thought this was going to be simpler, but given where we are now, I don't feel confident this is the right answer for most people.

**Comment by tmds** [comment]
> I am not ok with us creating coupling between the project file and the docker file where the dockerfile is responsible for the build and the project file is responsible for the copying and you need to carefully orchestrate those two things.

This coupling exists in any multi-stage build. You need to copy the assets from one stage to the other.

**Comment by tmds** [comment]
If the csproj file orchestrates placing the files during development.
The Dockerfile should defer that placement to the csproj file too.
Doing otherwise is asking for unintended differences.

**Comment by javiercn** [comment]
@tmds How is that different from doing the build in a separate stage? Don't you have to also replicate the commands there, which might also lead to differences?

**Comment by javiercn** [comment]
@tmds that logic in the csproj is just copying files from one folder to another, the same way the other logic is just running `npm install` or `npm run build` I don't see any meaningful difference between the two.

**Comment by tmds** [comment]
> I don't see any meaningful difference between the two.

1. It allows the Dockerfiles for angular and react to be the same.
2. Any changes made to the `ComputeFilesToPublish` file during development also take effect on the image build. Otherwise such changes need to be manually synced.

**Comment by javiercn** [comment]
> 1. It allows the Dockerfiles for angular and react to be the same. (Their `ComputeFilesToPublish` targets are slightly different.)

Why is that important? We could also make the csproj files similar and we chose not to do so.

> 2\. Any changes made to the `ComputeFilesToPublish` target during development also take effect on the image build. Otherwise such changes need to be manually synced to the `Dockerfile`.

The logic here is pretty straightforward and I don't think we'll be changing it any time soon based on the fact that we haven't changed it in the past. The only three things this does are:
* Install dependencies
* Run the build
* Copy the output

@tmds it feels like we are going back and forth, and we have different points of view on how this should fundamentally work. I understand that you have a desire to keep the Dockerfile the same between Angular/React and to have .NET handle the details of copying the files during the publish step.

On our side, we don't think there is any value in keeping the React/Angular Dockerfiles the same, since you are building one or the other and there are already differences in the csproj. We prefer a different approach where if you build in docker you take responsibility from doing the assets build as a whole in a separate container/stage and copying the results to the final build. 

We do not think that having differences between a Dockerfile for Angular or React are important and we believe it is more straightforward to have all the steps performed in the Dockerfile or in MSBuild rather than splitting the first part of the build into a separate stage and then rely on .NET on a separate stage to finish it. We believe it introduces a coupling that is not obvious and forces future changes to account for how a Dockerfile might be leveraging part of the pipeline, which makes changes much harder to reason about.

We understand that both have their pros and cons and that you favor a different approach. That said, I don't think we are willing to go that route for the reasons explained above.

This might not match your expectations; however, we hope that at least we were able to explain why we think we prefer to use a different approach.

**Comment by tmds** [comment]
I don't understand the 'coupling-issue'. All multi-stage builds copy artifacts between fixed directories.

Using `SpaRoot` gives you a well defined location for these artifacts.

It causes the `Dockerfile` build to behave the same as the `csproj` build.

How is this an issue?

**Comment by javiercn** [comment]
> I don't understand the 'coupling-issue'. All multi-stage builds copy artifacts between fixed directories.

I am not saying it is an issue, I am saying that it is not obvious that .NET handles the copy of the built assets in this case when it is not handling the install and building steps and that we favor a cleaner break where in docker the JS assets are built and handled externally, and .NET is not involved in the process if you choose to do a multi-stage build.

I took another look at the Dockerfile you provided on the issue, and I noticed something that I was missing before, which is the fact that you are copying some outputs from the node build to the .NET app before the publish step happens.

We think it is simpler to just do `COPY --from=node-build /src/ClientApp/dist /out/wwwroot` int the `# Build application image` than do a copy the bits into the .NET, have MSBuild publish the bits to the /out/wwwroot and then copy that to the final image.

> It causes the `Dockerfile` build to behave the same as the `csproj` build.

It already does not, you are already handling the install `(npm install)` and build `(npm run build -- --prod)` in a separate external step, why is copying the assets any different? 
What happens if tomorrow we decide to use different commands for react/angular? For example, what if tomorrow we decide to use yarn for react instead of NPM?

**Comment by tmds** [comment]
I see the value of leveraging the `SpaRoot` and `ComputeFilesToPublish` in the `Dockerfile` build.

Also with `yarn` that should be possible.

Anyway, let's agree to disagree.

**Pull request closed without merging**
